version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Install Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
      - unzip terraform.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - rm terraform.zip

  pre_build:
    commands:
      - echo "Initialize and validate Terraform"
      - terraform --version
      - terraform init -input=false

  build:
    commands:
      - echo "Plan Terraform changes"
      - terraform plan -out=tfplan -input=false

  post_build:
    commands:
      - echo "Apply Terraform changes"
      - terraform apply -input=false -auto-approve tfplan
